### PR TITLE
Make things more amenable to forking

### PR DESCRIPTION
**Pull request by gregbeech**
The previous implementation of RabbitMQ adapter was functional in a single-threaded environment but wouldn't work properly in a pre-forking environment such as Passenger or Unicorn. This change gets rid of the static properties and adds a `reconnect!` method which can be called after forking.

### CODE REVIEW

**Comment by jphastings** [comment]
LGTM - gotta love the 📝

**Comment by mezis** [comment]
A suggestion: wouldn't it be better to disconnect before forking, and add auto-reconnect support?
Bunny is very disconnect-prone, as I've had to work around time and time again.
See for instance [this](https://github.com/deliveroo/orderweb/blob/master/lib/roo/message_queue/bunny_adapter.rb#L57-L83) (in the Deliveroo app) or [this](https://github.com/HouseTrip/routemaster/blob/master/routemaster/models/bunny_channel.rb#L12-L19) (in another message bus implementation).

**Comment by gregbeech** [comment]
Probably yeah, I hadn't really spent any time looking at the reconnections etc. was just looking at getting the structure of the code approximately right to start. Happy to include that in this PR though.

**Comment by gregbeech** [comment]
@mezis updated the code based on some of the stuff we already had for handling retries and reconnections, though have modified it a bit to keep connections thread-local. Want to take another look?

**Pull request merged**
